export default {
	'zotero.appName': 'Zotero',
	'general.etAl': '等人',
	'general.back': '返回',
	'general.thanksForHelpingImprove': '感谢您帮助改进 %S！',
	'general.tryAgain': '重试',
	'general.updateAvailable': '更新可用',
	'general.copyToClipboard': '复制到剪贴板',
	'general.finished': '已完成',
	'general.checkForUpdates': '检查更新',
	'general.keys.cmdShift': 'Cmd+Shift+',
	'general.clear': '清除',
	'general.failed': '失败',
	'general.restartLater': '稍后重启',
	'general.unknownErrorOccurred': '发生未知错误。',
	'general.dontShowAgainFor': '今天不再显示;%1$S 天内不再显示',
	'general.permissionDenied': '权限被拒绝',
	'general.checkForUpdate': '检查更新',
	'general.moreInformation': '更多信息',
	'general.quitApp': '退出 %S',
	'general.errorHasOccurred': '发生错误。',
	'general.and': '和',
	'general.isUpToDate': '%S 已是最新版本。',
	'general.seeForMoreInformation': '查看 %S 获取更多信息。',
	'general.success': '成功',
	'general.submitted': '已提交',
	'general.character.plural': '字符',
	'general.locate': '定位…',
	'general.restartNow': '立即重启',
	'general.pleaseRestart': '请重启 %S。',
	'general.quit': '退出',
	'general.hide': '隐藏',
	'general.browserIsOffline': '%S 当前处于离线模式。',
	'general.error': '错误',
	'general.import': '导入',
	'general.warning': '警告',
	'general.yes': '是',
	'general.useDefault': '使用默认值',
	'general.fix': '修复…',
	'general.restartRequiredForChanges': '需要重启 %S 以使更改生效。',
	'general.accessDenied': '访问被拒绝',
	'general.continue': '继续',
	'general.dontShowAgain': '不再显示',
	'general.copy': '复制',
	'general.keys.ctrlShift': 'Ctrl+Shift+',
	'general.close': '关闭',
	'general.create': '创建',
	'general.export': '导出',
	'general.noUpdatesFound': '未找到更新',
	'general.restartRequired': '需要重启',
	'general.actionCannotBeUndone': '此操作无法撤销。',
	'general.pdf': 'PDF',
	'general.remove': '移除',
	'general.cancel': '取消',
	'general.tryLater': '稍后重试',
	'general.operationInProgress.waitUntilFinishedAndTryAgain': '请等待操作完成后重试。',
	'general.processing': '处理中',
	'general.disable': '禁用',
	'general.restartApp': '重启 %S',
	'general.enable': '启用',
	'general.showDirectory': '显示目录',
	'general.passed': '通过',
	'general.invalidResponseServer': '服务器响应无效。',
	'general.reset': '重置',
	'general.nMegabytes': '%S MB',
	'general.numMore': '还有 %S 个…',
	'general.serverError': '服务器返回错误。请重试。',
	'general.upgrade': '升级',
	'general.open': '打开 %S',
	'general.openPreferences': '打开首选项',
	'general.describeProblem': '简要描述问题：',
	'general.pleaseRestartAndTryAgain': '请重启 %S 后重试。',
	'general.operationInProgress.waitUntilFinished': '请等待操作完成。',
	'general.dontShowWarningAgain': '不再显示此警告。',
	'general.notNow': '暂不',
	'general.item': '项目',
	'general.restartRequiredForChange': '需要重启 %S 以使更改生效。',
	'general.character.singular': '字符',
	'general.operationInProgress': 'Zotero 操作正在进行中。',
	'general.no': '否',
	'general.delete': '删除',
	'general.openDocumentation': '打开文档',
	'general.tryAgainLater': '请几分钟后重试。',
	'general.install': '安装',
	'general.yellow': '黄色',
	'general.red': '红色',
	'general.green': '绿色',
	'general.blue': '蓝色',
	'general.purple': '紫色',
	'general.magenta': '品红色',
	'general.orange': '橙色',
	'general.gray': '灰色',
	'general.black': '黑色',
	'general.showInLibrary': '在库中显示',
	'general.clearSelection': '清除选择',
	'general.update': '更新',
	'general.print': '打印',
	'general.save': '保存',
	'general.edit': '编辑',
	'pdfReader.annotations': '注释',
	'pdfReader.showAnnotations': '显示注释',
	'pdfReader.searchAnnotations': '搜索注释',
	'pdfReader.searchOutline': '搜索大纲',
	'pdfReader.noAnnotations': '创建注释以在侧边栏中查看',
	'pdfReader.noExtractedText': '无提取文本',
	'pdfReader.addComment': '添加评论',
	'pdfReader.annotationComment': '注释评论',
	'pdfReader.annotationText': '注释文本',
	'pdfReader.manageTags': '管理此注释的标签',
	'pdfReader.openMenu': '打开注释菜单',
	'pdfReader.thumbnails': '缩略图',
	'pdfReader.tagSelectorMessage': '按此标签筛选注释',
	'pdfReader.addTags': '添加标签…',
	'pdfReader.highlightText': '高亮文本',
	'pdfReader.underlineText': '下划线文本',
	'pdfReader.addNote': '添加笔记',
	'pdfReader.selectArea': '选择区域',
	'pdfReader.addText': '添加文本',
	'pdfReader.draw': '绘图',
	'pdfReader.highlightAnnotation': '高亮注释',
	'pdfReader.underlineAnnotation': '下划线注释',
	'pdfReader.noteAnnotation': '笔记注释',
	'pdfReader.textAnnotation': '文本注释',
	'pdfReader.imageAnnotation': '图片注释',
	'pdfReader.inkAnnotation': '墨迹注释',
	'pdfReader.searchResultIndex': '搜索结果',
	'pdfReader.searchResultTotal': '搜索结果总数',
	'pdfReader.eraser': '橡皮擦',
	'pdfReader.pickColor': '选择颜色',
	'pdfReader.addToNote': '添加到笔记',
	'pdfReader.zoomIn': '放大',
	'pdfReader.zoomOut': '缩小',
	'pdfReader.zoomReset': '重置缩放',
	'pdfReader.zoomAuto': '自动调整大小',
	'pdfReader.zoomPageWidth': '适应页面宽度',
	'pdfReader.zoomPageHeight': '适应页面高度',
	'pdfReader.splitVertically': '垂直分割',
	'pdfReader.splitHorizontally': '水平分割',
	'pdfReader.nextPage': '下一页',
	'pdfReader.previousPage': '上一页',
	'pdfReader.page': '页面',
	'pdfReader.location': '位置',
	'pdfReader.readOnly': '只读',
	'pdfReader.promptTransferFromPDF.title': '导入注释',
	'pdfReader.promptTransferFromPDF.text': 'PDF 文件中存储的注释将被移动到 %1$S。',
	'pdfReader.promptTransferToPDF.title': '在文件中存储注释',
	'pdfReader.promptTransferToPDF.text': '注释将被转移到 PDF 文件中，并且在 %S 中将不再可编辑。',
	'pdfReader.promptPasswordProtected': '不支持对受密码保护的 PDF 文件执行此操作。',
	'pdfReader.rotateLeft': '向左旋转',
	'pdfReader.rotateRight': '向右旋转',
	'pdfReader.editPageNumber': '编辑页码…',
	'pdfReader.editAnnotationText': '编辑注释文本',
	'pdfReader.copyImage': '复制图片',
	'pdfReader.saveImageAs': '图片另存为…',
	'pdfReader.pageNumberPopupHeader': '更改页码：',
	'pdfReader.thisAnnotation': '此注释',
	'pdfReader.selectedAnnotations': '已选择的注释',
	'pdfReader.thisPage': '此页',
	'pdfReader.thisPageAndLaterPages': '此页及后续页面',
	'pdfReader.allPages': '所有页面',
	'pdfReader.autoDetect': '自动检测',
	'pdfReader.appearance': '外观',
	'pdfReader.epubAppearance.lineHeight': '行高',
	'pdfReader.epubAppearance.wordSpacing': '字间距',
	'pdfReader.epubAppearance.letterSpacing': '字母间距',
	'pdfReader.epubAppearance.pageWidth': '页面宽度',
	'pdfReader.epubAppearance.useOriginalFont': '使用原始字体',
	'pdfReader.epubAppearance.lineHeight.revert': '使用默认行高',
	'pdfReader.epubAppearance.wordSpacing.revert': '使用默认字间距',
	'pdfReader.epubAppearance.letterSpacing.revert': '使用默认字母间距',
	'pdfReader.epubAppearance.pageWidth.revert': '使用默认页面宽度',
	'pdfReader.deleteAnnotation.singular': '确定要删除选中的注释吗？',
	'pdfReader.deleteAnnotation.plural': '确定要删除选中的注释吗？',
	'pdfReader.enterPassword': '请输入密码以打开此 PDF 文件。',
	'pdfReader.includeAnnotations': '包含注释',
	'pdfReader.preparingDocumentForPrinting': '正在准备打印文档…',
	'pdfReader.phraseNotFound': '未找到短语',
	'pdfReader.selectedPages': '已选择 {count, plural, one {# 页} other {# 页}}',
	'pdfReader.pageOptions': '页面选项',
	'pdfReader.epubEncrypted': '此电子书似乎已加密，无法打开。',
	'pdfReader.find': '查找',
	'pdfReader.close': '关闭',
	'pdfReader.showThumbnails': '显示缩略图',
	'pdfReader.showOutline': '显示大纲',
	'pdfReader.findPrevious': '查找上一个匹配项',
	'pdfReader.findNext': '查找下一个匹配项',
	'pdfReader.toggleSidebar': '切换侧边栏',
	'pdfReader.findInDocument': '在文档中查找',
	'pdfReader.toggleContextPane': '切换上下文面板',
	'pdfReader.highlightAll': '全部高亮',
	'pdfReader.matchCase': '区分大小写',
	'pdfReader.wholeWords': '全字匹配',
	'pdfReader.convertToHighlight': '转换为高亮',
	'pdfReader.convertToUnderline': '转换为下划线',
	'pdfReader.size': '大小',
	'pdfReader.merge': '合并',
	'pdfReader.copyLink': '复制链接',
	'pdfReader.theme.original': '原始',
	'pdfReader.theme.snow': '雪白',
	'pdfReader.theme.sepia': '棕褐',
	'pdfReader.theme.dark': '深色',
	'pdfReader.addTheme': '添加主题',
	'pdfReader.scrollMode': '滚动',
	'pdfReader.spreadMode': '跨页',
	'pdfReader.flowMode': '页面布局',
	'pdfReader.columns': '列',
	'pdfReader.splitView': '分屏视图',
	'pdfReader.themes': '主题',
	'pdfReader.vertical': '垂直',
	'pdfReader.horizontal': '水平',
	'pdfReader.wrapped': '自动换行',
	'pdfReader.none': '无',
	'pdfReader.odd': '奇数页',
	'pdfReader.even': '偶数页',
	'pdfReader.paginated': '分页',
	'pdfReader.scrolled': '滚动',
	'pdfReader.single': '单页',
	'pdfReader.double': '双页',
	'pdfReader.themeName': '主题名称：',
	'pdfReader.background': '背景：',
	'pdfReader.foreground': '前景：',
};
